### PR TITLE
fixed "fluid.html.html" typo; restored missing landing page content

### PR DESCRIPTION
**Pull request by hmcc**
Hi,
I've just started working with the hyde-bootstrap template, and it's great. Thank you!

I've fixed a couple of things:
1. in index.html, "fluid.html" had the file extension shown twice ("fluid.html.html")
2. most of landing.html was missing for me (using hyde 0.8.7), but changing "content" to "container" fixed it.

Thanks again for providing this template, I've found it very useful.

Cheers,
Heather

### CODE REVIEW

**Comment by blanchardjeremy** [comment]
Thanks! :)

**Comment by hmcc** [comment]
You're welcome :)

I'm probably going to upgrade my branch to Bootstrap 3, and add another page for a blog (something like the Hyde "basic" template, but with Bootstrap styling).

Do you want either or both of those too?

**Comment by blanchardjeremy** [comment]
Yeah both of those sound like great additions. 

I don't plan on actively improving this repo myself, but I'm happy to take pull requests and have this repo be a hub for the work that others want to do since it's so well-followed at this point.

**Comment by hmcc** [comment]
Great, I wasn't sure whether you just wanted bug fixes or whether you were happy with bigger changes. I'll get those done sometime next week and send you another pull request.

**Comment by blanchardjeremy** [comment]
Yeah, totally. Thanks for contributing, @hmcc! You're awesome! :)

**Comment by hmcc** [comment]
Thanks for making my first contribution on GitHub so easy! Another pull request coming up...

**Pull request merged**
